language: julia
os:
  - linux
  - osx
julia:
  - 0.5
  - nightly
notifications:
  email: false
addons:
  apt:
    packages:
    - cmake
    - libxxf86vm-dev
    sources:
    - kubuntu-backports
before_script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - LIBGL_ALWAYS_SOFTWARE=1 julia --check-bounds=yes --depwarn=no -e 'Pkg.clone(pwd()); Pkg.build("GLFW"); Pkg.test("GLFW"; coverage=true)'
