language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email: false
before_install:
  - sudo add-apt-repository ppa:kalakris/cmake -y # Newer CMake
  - sudo apt-get update -qq
install:
  - sudo apt-get install -y cmake libXxf86vm-dev  # GLFW dependencies
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start" # X virtual framebuffer
