language: julia
os:
  - linux
  - osx
julia:
  - 0.5
  - nightly
notifications:
  email: false
addons:
  apt:
    packages:
    - cmake
    - libxxf86vm-dev
    sources:
    - kubuntu-backports
before_install:
  - sudo apt-get install xpra xserver-xorg-video-dummy freeglut3-dev;
before_script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; "xpra --xvfb=\"Xorg +extension GLX -config `pwd`/test/dummy.xorg.conf -logfile ${HOME}/.xpra/xorg.log\"  start :9"; fi
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - LIBGL_ALWAYS_SOFTWARE=1 DISPLAY=:9 julia --check-bounds=yes --depwarn=no -e 'Pkg.clone(pwd()); Pkg.build("GLFW"); Pkg.test("GLFW"; coverage=true)'
